opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - direct_return
  - discouraged_assert
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - joined_default_parameter
  - last_where
  - multiline_arguments
  - multiline_arguments_brackets
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - return_value_from_void_function
  - sorted_imports
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
trailing_comma:
  mandatory_comma: true
identifier_name:
  min_length:
    warning: 1
    error: 1
  validates_start_with_lowercase: off
type_name:
  min_length:
    warning: 1
    error: 1
  validates_start_with_lowercase: off
nesting:
  type_level:
    warning: 3
    error: 5
analyzer_rules:
  - unused_declaration
  - capture_variable
  - unused_import
included:
  - Sources
  - Tests
  - Package.swift
strict: true
line_length: 120
reporter: "xcode"