name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - './**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
      - run: swift test